version: 2
jobs:
  DataBase:
    docker:
      - image: gradle:jdk11
    steps:
      - checkout
      - run: cd DataBase && ./gradlew build
  smartlist:
    docker:
      - image: gradle:jdk11
    steps:
      - checkout
      - run: cd smartlist && ./gradlew build
  hashtable:
    docker:
      - image: gradle:jdk11
    steps:
      - checkout
      - run: cd hashtable && ./gradlew build
  trie:
    docker:
      - image: gradle:jdk11
    steps:
      - checkout
      - run: cd trie && ./gradlew build
workflows:
  version: 2
  DataBase:
    jobs:
      - DataBase
  smartlist:
    jobs:
      - smartlist
  hashtable:
    jobs:
      - hashtable
  trie:
    jobs:
      - trie
